version: "3.7"

services:
  db:
    image: postgres:12
    ports:
      - "25439:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend
    volumes:
      - postgre_db:/var/lib/postgresql/data

volumes:
  postgre_db:
